### ISSUE TITLE
Не все сервисы есть в DiadocApi. Например GenerateDocumentZip и ShelfDownload

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#102]
Не все сервисы есть в DiadocApi. Например GenerateDocumentZip и ShelfDownload
https://api-docs.diadoc.ru/ru/latest/http/GenerateDocumentZip.html
https://api-docs.diadoc.ru/ru/latest/http/ShelfDownload.html
Для самостоятельной их обработки достаточно выпустить в public PerformHttpRequest
Например так
**DiadocApi.h**
public
  DiadocApi::Bytes_t PerformHttpRequestGet(const std::wstring& queryString);

**DiadocApi.cpp**

DiadocApi::Bytes_t DiadocApi::PerformHttpRequestGet(const std::wstring& queryString)
{
	WppTraceDebugOut(L"PerformHttpRequestGet...");
	return PerformHttpRequest(queryString, GET);

}
Все остальное уже смогут сделать сами. 
Номер обращения в диадоке - 24884324.
С такой доработкой проблема уже решена, но хочется, чтобы она вошла в стандартный пакет.

Если вы не против я могу попробовать сделать Pull Request - но не вижу, чтобы кто то их делал.

**Comment by flosca** [comment]
Привет!

Спасибо за пулл-реквест. Однако, мы не можем его принять по следующим соображениям:

1. В частном, такой метод не совсем верно работает, например, для `GenerateDocumentZip`: например, не учитывается случай, когда архив не успеет собраться, и метод не вернет путь до полки, а вернет заголовок `Retry-After`.
2. В общем, SDK это набор конкретных методов вокруг HTTP-API. Создавать некий god-object в виде общего гет-запроса означает не совсем правильное использование SDK. 

Да, к сожалению, не все методы из HTTP-API представлены в SDK, но в таком случае лучше либо попросить нас добавить недостающие методы через `issue`, либо через `PR` самим сделать конкретные реализации.

GenerateDocumentZip и ShelfDownload я добавил в последнем релизе. Можете обновить библиотеку и заиспользовать их.
https://github.com/diadoc/diadocsdk-cpp/releases/tag/versions%2F1.82.2
