### ISSUE TITLE
Перестал работать метод GenerateDocumentZip с ошибкой 400 Could not get boxId from query param

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#117]
Добрый день.
Прошу прощения, Промахнулся проектом в
https://github.com/diadoc/diadocsdk-csharp/issues/852
но cSharp тоже есть в тестовом варианте - пока руки не дошли посмотреть им.

Используется апи diadocsdk-cpp-versions-1.92.3.zip
Но проблема возникла еще на diadocsdk-cpp-versions-1.92.0.zip 28.06.2021.
У нас повторилась. На момент проверки ничего не менялось с марта 2021( тогда был переход на апи 1.92.0).
Возможно связано с переходом на V3
Вот здесь осталось
TaskResult DiadocApi::GenerateDocumentZip(const std::wstring& boxId, const std::wstring& messageId, const std::wstring& documentId, bool fullDocflow)
{
std::wstringstream buf;
buf << "?boxId=" << StringHelper::CanonicalizeUrl(boxId) << L"&messageId=" << StringHelper::CanonicalizeUrl(messageId) << L"&documentId=" << StringHelper::CanonicalizeUrl(documentId);

Ну и наверное проблема будет в ShelfDownload
В других местах buf << L"/V3/GetDocuments?boxId="

**Comment by Edw-K** [comment]
В общем выяснил, что причина в
GenerateDocumentZip(
buf << "**?**boxId=" << StringHelper::CanonicalizeUrl(boxId) << L"&messageId=" << StringHelper::CanonicalizeUrl(messageId) << L"&documentId=" << StringHelper::CanonicalizeUrl(documentId);
Знак вопроса лишний. 
В итоге получил такую строку запроса 
PerformAsyncHttpRequest /GenerateDocumentZip??boxId=2c47a7a.........

Просьба исправить. Видимо раньше ?? гасилось.
В C# не смотрел в чем причина, но такая же ошибка там тоже есть.
Хорошо бы, чтобы была возможность добавить режим вывода протокола запроса.
Я для поиска сделал так
void AddProtocolAPI(std::string str)
{
	std::ofstream fout("diadoc_dll.log", std::ios_base::app);
	fout << str << "\n";
	fout.close();
}
А в функции вызвал
	AddProtocolAPI("PerformAsyncHttpRequest " + StringHelper::Utf16ToUtf8(buf.str() ));
Или просьба подсказать, чем можно проследить запросы к апи.

**Comment by Dmitriy-Ipatyev** [comment]
Привет! Обновите сдк. В последней версии как раз это пофиксили https://github.com/diadoc/diadocsdk-cpp/releases/tag/versions%2F1.92.5

**Comment by Edw-K** [comment]
Спасибо. На последней версии все работает.
