### ISSUE TITLE
Клиент просит поле "Дата изменения статуса" из справочника контрагентов.

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#118]
В справочнике мои контрагенты
![изображение](https://user-images.githubusercontent.com/61151186/124549127-655b9380-de37-11eb-8a23-af24e1bfdcdf.png)
Не нашел такого поля в структуре Counteragent
Есть поле LastEventTimestampTicks - метка времени последнего события из истории взаимодействия с данным контрагентом
Это оно? По комментарию не совсем подходит.
Если нет, просьба добавить в обмен.
Собственно клиенту нужно "дата, в которую контрагенты добавили друг друга в список контрагентов в Диадоке" и привели этот скрин.

**Comment by aeremina88** [comment]
Да, это оно.

**Comment by Edw-K** [comment]
Спасибо.
