### ISSUE TITLE
Нет функции GetMyCertificates

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#120]
в c# есть. Просьба добавить. GetMyUser -> User не содержит моего сертификата.

**Comment by ichechulina** [comment]
Добрый день, добавили.

**Comment by lalexs75** [comment]
Добрый день. 
Можно уточнить - в чём различие между файлами https://github.com/diadoc/diadocsdk-cpp/blob/master/proto/CertificateInfoV2.proto и https://github.com/diadoc/diadocsdk-cpp/blob/master/proto/Certificates/CertificateInfoV2.proto
аналогично для файлов с именем CertificateList.proto

**Comment by Edw-K** [comment]
https://diadoc-sdk.readthedocs.io/ru/latest/proto/User.html?highlight=CertificateInfo#user
https://diadoc-sdk.readthedocs.io/ru/latest/http/GetMyCertificates.html
немного разный состав объектов.
В принципе User +CertificateInfo почти = CertificateInfoV2, но вот список должен быть несколько разный по описанию. 
Я пока не проверил.

**Comment by Edw-K** [comment]
Проверил. GetMyCertificates  работает. Спасибо.
