### ISSUE TITLE
Когда будет добавлена функциональность для работы с машиночитаемой доверенностью в c++?

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#125]
https://developer.kontur.ru/docs/diadoc-api/ReleaseNotes.html указано, что функционал добавлен для Java и c#
А когда это будет добавлено для с++ и будет ли вообще?

**Comment by ilzag** [comment]
Добрый день!
Задача в работе у разработчиков, точный срок введения в работу пока не можем назвать.

**Comment by ilzag** [comment]
Добрый день! Было принято решение отказаться от поддержки SDK C++. [Новость на нашем сайте](https://www.diadoc.ru/blog/47067-prekrashhaetsya_obnovlenie_sdk_c_v_api_diadoka).
