### ISSUE TITLE
Нет функции GetResolutionRoutesForOrganization

### ISSUE THREAD

**Issue by Edw-K** [diadoc/diadocsdk-cpp#129]
https://developer.kontur.ru/Docs/diadoc-api/http/GetResolutionRoutesForOrganization.html
объект ResolutionRouteList есть в ResolutionRouteList.pb.h

**Comment by ilzag** [comment]
Добрый день!
На данный момент [функция ](https://github.com/search?q=repo%3Adiadoc%2Fdiadocsdk-cpp%20GetResolutionRoutesForOrganization&type=code)добавлена. Проверьте, пожалуйста.
