### ISSUE TITLE
ФИО подписанта в документе не совпадает с ФИО владельца электронной подписи

### ISSUE THREAD

**Issue by purerere** [diadoc/diadocsdk-cpp#13]
добрый день!
потребовалось добавить проверку на соответствие ФИО подписанта с ФИО владельца ЭП.

если они расходятся, в личном кабинете всплывает под шапкой документа такое предупреждение.
как на уровне API это узнать?
есть ли готовый флаг, который это бы обозначал или нужно сверять самому? 

и если самому, то откуда взять данные о ФИО владельца ЭП.

заранее спасибо!

**Comment by asvyazin** [comment]
Готового флага сейчас нет, надо сверять самому. ФИО владельца берется из сертификата, который, на самом деле, всегда вкладывается в подпись. Для того, чтобы вытащить сертификат из подписи и ФИО из сертификата, придется использовать, вероятно, какие-то сторонние библиотеки.
