### ISSUE TITLE
ГОСТ 34.11-2012

### ISSUE THREAD

**Issue by YuriMorozov** [diadoc/diadocsdk-cpp#75]
https://github.com/diadoc/diadocsdk-cpp/blob/master/src/Certificate.cpp
Метод 
Certificate::Bytes_t Certificate::Sign(const Bytes_t& input) const
работает только с алгоритмом шифрования по ГОСТ 34.11-94. 
Сейчас пользователям стали выдавать сертификаты по ГОСТ 34.11-2012

Можно доработать данный метод?

**Comment by i82** [comment]
Мы себе поставили задачу в очередь. По срокам пока не сориентирую.
Можете сделать PR самостоятельно, если вам критичны сроки; мы его примем.

**Comment by halex2005** [comment]
@YuriMorozov, попробуйте использовать бинарники отсюда #76? https://ci.appveyor.com/project/diadoc-admin/diadocsdk-cpp/builds/22449030/job/8n7ut1rjyklhse53/artifacts

Предлагаю убедиться, что теперь можно будет подписывать обоими типами сертов - ГОСТ 2001 и ГОСТ 2012.

**Comment by YuriMorozov** [comment]
К сожалению не могу проверить у себя, нет действующих сертификатов. 

Выложите исходники, гляну. Мы для клиентов Галактики временно сделали заплатку, через некоторое время пересоберем с учетом вашего решения. Тогда и проверим.

**Comment by halex2005** [comment]
@YuriMorozov, исходники можете найти в #76 или https://github.com/halex2005/diadocsdk-cpp/tree/gost2012

**Comment by halex2005** [comment]
@YuriMorozov, я проверил, подписать получилось. PR #76 принят, поддержка подписания ГОСТ2012 появилась в версии SDK 1.64.1 и выше.
