### ISSUE TITLE
GenerateSenderTitleXml

### ISSUE THREAD

**Issue by purerere** [diadoc/diadocsdk-cpp#89]
Здравствуйте!

Добавляю поддержку **УПД-820**, не получается понять откуда получить **userContractData** для передачи в **GenerateSenderTitleXml**.

В SDK для C# есть разбор этой темы здесь: 
https://github.com/diadoc/diadocsdk-csharp/issues/490 

Однако, я не могу найти никаких хотя бы похожих классов **Utd820.UniversalTransferDocument** и объявлений **SerializeToXml()** для сериализации.

Или в C# версии SDK это уже реализовано, а в C++ пока нет?
Заранее спасибо за ответ.

**Comment by etwirt** [comment]
Добрый день!
Классы для генерации xml не планируется добавлять, это осознанный подход. Клиенты апи должны сами каким-то образом получать xml.
Можно использовать xsd.exe для генерации класса по xsd-схеме, в экземпляре класса заполнять данные и сериализовать в xml.

**Comment by purerere** [comment]
Подскажите, пожалуйста, почему тогда в версии SDK для C# подход отличается от версии для C++? Там вы создали этот класс, а здесь осознанно нет...

**Comment by NataliaShumikhina** [comment]
Добрый день! Изначально мы осознанно не хотели создавать отдельный класс даже в C#, но в ходе переговоров и работы над задачей пошли на встречу нашим интеграторам и добавили классы только в C#

**Comment by purerere** [comment]
> Добрый день! Изначально мы осознанно не хотели создавать отдельный класс даже в C#, но в ходе переговоров и работы над задачей пошли на встречу нашим интеграторам и добавили классы только в C#

Ясно... Перепишу с C#, что поделать.
